version: '2'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    container_name: cheap-route
    links:
      - mongodb
  mongodb:
    image: mongo:3.4
    container_name: cheap-route-mongodb
    volumes:
      - ./docker/mongodb/data:/data/db